// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnTLlerNIJFHZR6dfA75f_3HbVQz9BjsQ',
    appId: '1:207282525472:web:d0c87ee622d1589fb43345',
    messagingSenderId: '207282525472',
    projectId: 'pmobile9-635dd',
    authDomain: 'pmobile9-635dd.firebaseapp.com',
    storageBucket: 'pmobile9-635dd.firebasestorage.app',
    measurementId: 'G-P50YLL5JWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2xmIkYkiiQgkE4IXXoAU_lPlC4_5DZAU',
    appId: '1:207282525472:android:241eeeb80c70b6a8b43345',
    messagingSenderId: '207282525472',
    projectId: 'pmobile9-635dd',
    storageBucket: 'pmobile9-635dd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnTLlerNIJFHZR6dfA75f_3HbVQz9BjsQ',
    appId: '1:207282525472:web:21b47f4012264539b43345',
    messagingSenderId: '207282525472',
    projectId: 'pmobile9-635dd',
    authDomain: 'pmobile9-635dd.firebaseapp.com',
    storageBucket: 'pmobile9-635dd.firebasestorage.app',
    measurementId: 'G-2HHRJ205WJ',
  );
}
